openapi: 3.0.0
info:
  title: Social Media API
  version: 1.0.0
  description: |
    This is from YAML File based application of swagger documentation

    This is the social media api created based on the backend training project document.

    Some useful links: 
    - [The Backend training repository(public)](https://github.com/kdahiya-hc/backendtraining)

servers:
  - url: http://localhost:8000
    description: Development environment

paths:
  /{number}:
    get:
      tags:
        - /:number
      summary: Check if a number is odd or even
      security:
        - xAuthToken: []
      description: |
        Given a number in the URL path, the endpoint checks if the number is odd or even.

        If no number is passed, or if the value is not a number, it returns a 400 error.
      parameters:
        - in: path
          name: number
          required: true
          description: The number to check
          schema:
            example: 5
      responses:
        200:
          description: Successfully received the number and checked if it is odd or even
          content:
            application/json:
              schema:
                # $ref: '#/components/schemas/defaultResponse'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Number is even'
                  value:
                    type: object
                    properties:
                      number:
                        type: integer
                        example: 5
        400:
          description: Bad Request - The input was not a valid number
          content:
            application/json:
              schema:
                # $ref: '#/components/schemas/defaultResponse'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Pass a number'
                  value:
                    type: object
                    properties:
                      text:
                        type: string
                        example: 'hello'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                # $ref: '#/components/schemas/defaultResponse'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Internal server error'
                  value:
                    type: object
                    properties: {}

components:
  securitySchemes:
    xAuthToken:
      type: apiKey
      in: header
      name: x-auth-token
  schemas:
    defaultResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        value:
          type: object
      example:
        success: true
        message: string
        value: { key: value }
